trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  acrServiceConnection: 'hina-acr-connection'
  repositoryName: 'hina-secure-app'
  imageTag: '$(Build.BuildId)' 

stages:
# 🛡️ NEW DEVSECOPS STAGE 🛡️
- stage: SecurityScan
  displayName: 'DevSecOps: Vulnerability Scan'
  jobs:
  - job: TrivyScan
    displayName: 'Scan Code & Dependencies'
    steps:
    - bash: |
        echo "⬇️ Downloading Trivy Scanner..."
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin
        
        echo "🔍 Running Trivy Security Scan on Repository..."
        # Note: Abhi humne --exit-code 0 rakha hai taake pipeline fail na ho (Audit Mode).
        # Strict enterprise env mein isay --exit-code 1 kar dete hain taake critical issues par build ruk jaye.
        trivy fs --severity HIGH,CRITICAL --exit-code 0 --no-progress .
      displayName: 'Run Aqua Security Trivy Scan'

# 🏗️ EXISTING BUILD STAGE (Now depends on SecurityScan)
- stage: BuildAndPush
  displayName: 'Build and Push Stage'
  dependsOn: SecurityScan
  jobs:
  - job: Build
    displayName: 'Docker Build & Registry Push'
    steps:
    - task: Docker@2
      displayName: 'Build and Push to Azure Container Registry'
      inputs:
        command: 'buildAndPush'
        containerRegistry: '$(acrServiceConnection)'
        repository: '$(repositoryName)'
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(imageTag)
          latest

# 🔄 EXISTING GITOPS STAGE
- stage: UpdateManifests
  displayName: 'Update GitOps Manifests'
  dependsOn: BuildAndPush
  jobs:
  - job: UpdateGit
    displayName: 'Git Push New Image Tag'
    steps:
    - bash: |
        git config --global user.email "hinanaseer13@gmail.com"
        git config --global user.name "Hina Naseer"
        
        git clone https://$(githubToken)@github.com/hinanaseer/hina-gitops-manifests.git
        cd hina-gitops-manifests
        
        sed -i "s|hinaksaacr.azurecr.io/hina-secure-app:.*|hinaksaacr.azurecr.io/hina-secure-app:$(imageTag)|g" deployment.yaml
        
        git add deployment.yaml
        git commit -m "automation: update deployment image tag to $(imageTag) [skip ci]"
        git push origin main
      displayName: 'Sed Update and Push to Manifest Repo'
      env:
        MY_SECURE_TOKEN: $(GITHUB_PAT)