trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  acrServiceConnection: 'hina-acr-connection'
  repositoryName: 'hina-secure-app'
  imageTag: '$(Build.BuildId)' 

stages:
- stage: BuildAndPush
  displayName: 'Build and Push Stage'
  jobs:
  - job: Build
    displayName: 'Docker Build & Registry Push'
    steps:
    - task: Docker@2
      displayName: 'Build and Push to Azure Container Registry'
      inputs:
        command: 'buildAndPush'
        containerRegistry: '$(acrServiceConnection)'
        repository: '$(repositoryName)'
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(imageTag)
          latest

- stage: UpdateManifests
  displayName: 'Update GitOps Manifests'
  dependsOn: BuildAndPush
  jobs:
  - job: UpdateGit
    displayName: 'Git Push New Image Tag'
    steps:
    - bash: |
        # 1. Git config set up karo
        git config --global user.email "hinanaseer13@gmail.com"
        git config --global user.name "Hina Naseer"
        
        # 2. Variable ke zariye securely clone karo 
        # (Yahan $MY_SECURE_TOKEN us environment variable ko call kar raha hai jo hum ne niche define kiya hai)
        git clone https://$(githubToken)@github.com/hinanaseer/hina-gitops-manifests.git
        
        # 3. Cloned folder ke andar jao
        cd hina-gitops-manifests
        
        # 4. deployment.yaml ke andar image tag ko naye BuildId se update karo
        sed -i "s|hinaksaacr.azurecr.io/hina-secure-app:.*|hinaksaacr.azurecr.io/hina-secure-app:$(imageTag)|g" deployment.yaml
        
        # 5. Changes ko GitHub par push karo
        git add deployment.yaml
        git commit -m "automation: update deployment image tag to $(imageTag) [skip ci]"
        git push origin main
      displayName: 'Sed Update and Push to Manifest Repo'
      env:
        # Aap ke Azure DevOps GUI variable ko yahan script ke sath link kar rahe hain
        MY_SECURE_TOKEN: $(GITHUB_PAT)